name: Telegram Config Sender

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          TARGET_CHANNEL: ${{ secrets.TARGET_CHANNEL }}
        run: python main.py
